# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: R-full

jobs:
  macOS:
    runs-on: macOS-latest
    strategy:
      matrix:
      #  r: ['4.0', 'devel']
        r:['devel']
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.r }}
      - uses: r-lib/actions/setup-pandoc@master
      - uses: r-lib/actions/setup-tinytex@master
      - name: Install dependencies
        env:
          R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
        run: Rscript -e "install.packages(c('remotes', 'rcmdcheck'))" -e "remotes::install_deps(dependencies = TRUE)"
      - name: Check
        run: Rscript -e "rcmdcheck::rcmdcheck(error_on = 'error')"
      - name: Test coverage
        if: matrix.r == 'devel'
        run: |
          Rscript -e 'remotes::install_github("r-lib/covr@gh-actions")'
          Rscript -e 'covr::codecov(token = "${{secrets.CODECOV_TOKEN}}")'
 # linux:
 #   runs-on: ubuntu-latest
    #strategy:
    #  matrix:
    #    r: ['4.0']
 #   container: rstudio/r-base:${{ matrix.r }}-xenial
 #   env:
 #     CRAN: 'https://demo.rstudiopm.com/all/__linux__/xenial/latest'
 #   steps:
 #     - uses: actions/checkout@v1
 #     - uses: r-lib/actions/setup-r@master
 #     - uses: r-lib/actions/setup-pandoc@master
 #     - uses: r-lib/actions/setup-tinytex@master
 #     - name: Install dependencies
 #       run: |
 #         Rscript -e "install.packages('remotes')" -e "remotes::install_github('r-hub/sysreqs')"
 #         sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
 #         eval "$sysreqs"
 #         Rscript -e "remotes::install_deps(dependencies = TRUE)"
 #       env:
 #         RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
 #     - name: Check
 #       run: Rscript -e "install.packages('rcmdcheck')" -e "rcmdcheck::rcmdcheck(error_on = 'error')"

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - uses: r-lib/actions/setup-tinytex@master
      - name: Install dependencies
        run: Rscript -e "install.packages(c('remotes', 'rcmdcheck'))" -e "remotes::install_deps(dependencies = TRUE)"
      - name: Check
        run: Rscript -e "rcmdcheck::rcmdcheck(error_on = 'error')"
